version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:7070"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis:6379
  redis:
    image: "redis:6.2.5"
    ports:
      - "6379:6379"